<template>
    <div>
     <div class="container-fluid">

    <div class="row">
    <div class="col-8 mx-auto mt-5 w-100 text-center">
                 
    <h5 class="font-weight-bold text-primary ml-3">
    <i class="fas fa-poo-storm"></i> SnapBank</h5> 
    <p class="font-weight-bold"><i class="fas fa-pause-circle"></i> Dear <span class="text-primary"> {{userName.toUpperCase()}}</span>, please wait while we set up your account..</p>  <br>

    <p class="text-info font-weight-bold" v-show="verify">Verifying your informations </p>
    <p class="text-success font-weight-bold" v-show="create">Informations verified, account being created </p>
    <p class="text-primary font-weight-bold" v-show="ready"><i class="fas fa-thumbs-up"></i> Fantastic, your account is ready, you'll be redirected to the login page </p>

    <div class="loadingio-spinner-eclipse-0tuftxinm0z mt-2"><div class="ldio-cbxxel8yix7">
    <div></div>
    </div></div> <br>


     <small class="font-weight-bold color"> Your account will be ready in a few..</small>
     <small class="font-weight-bold text-primary"> Thanks for your patience. <i class="fas fa-handshake"></i></small>            
    </div>  

    </div>

         
         
         </div>  
   
    </div>
</template>
<script>

export default {
    name:'Setup',
    

    data(){
        return{
            verify: true,
            create: false,
            ready: false,
            userName: this.$route.params.id,
            num: 10,
          
        }


    
    },

    methods: {
       

    },

    created(){
        setTimeout(()=>  this.verify = false, 2000)
        setTimeout(()=>  this.create = true, 2000)
        setTimeout(()=>  this.create = false, 9000)
        setTimeout(()=>  this.ready = true, 4000)
        setTimeout(()=>  this.$router.push({path: '/loginpage'}), 6000);
        
       
    
        
    },


   
}
</script>
<style scoped>
 

@keyframes ldio-cbxxel8yix7 {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.ldio-cbxxel8yix7 div {
  position: absolute;
  animation: ldio-cbxxel8yix7 1s linear infinite;
  width: 160px;
  height: 160px;
  top: 20px;
  left: 20px;
  border-radius: 50%;
  box-shadow: 0 4px 0 0 #007bff;
  transform-origin: 80px 82px;
}
.loadingio-spinner-eclipse-0tuftxinm0z {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-cbxxel8yix7 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-cbxxel8yix7 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>  
